### ISSUE TITLE
git.launchpad.net should be marked as deprecated

### ISSUE THREAD

**Issue by nobuto-m** [canonical/ua-reviewkit#16]
I understand that now the development of ua-reviewkit is done on Github instead of Launchpad. But git.launchpad.net still has content and hard to notice it's deprecated.

Can we add one commit to the git by deleting everything but leaving one README file saying we should refer to https://github.com/canonical/ua-reviewkit from now on? So we can avoid confusions.
https://git.launchpad.net/ua-reviewkit/tree/

P.S. I found it by one handover still using git.launchpad.net as the source of some tests.

**Comment by dosaboy** [comment]
Done. See https://git.launchpad.net/ua-reviewkit/commit/?id=d642778a97ca8a3a30da5e15f9f33477b73200fd.

**Comment by nobuto-m** [comment]
Perfect, thanks!
