### ISSUE TITLE
image from projects.registry.vmware.com/sonobuoy/sonobuoy does not work anymore

### ISSUE THREAD

**Issue by SMAK1993** [canonical/ua-reviewkit#19]
I tried to run the kubernetes-extra-checks.py script and my script got stuck trying to pull the sonobuoy image from projects.registry.vmware.com/sonobuoy/sonobuoy.

The pod description reported the following errors:
```
  Normal   Scheduled  44s                default-scheduler  Successfully assigned sonobuoy/sonobuoy to juju-29bbea-kubernetes-10
  Normal   BackOff    14s (x2 over 42s)  kubelet            Back-off pulling image "projects.registry.vmware.com/sonobuoy/sonobuoy:v0.56.3"
  Warning  Failed     14s (x2 over 42s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    3s (x3 over 43s)   kubelet            Pulling image "projects.registry.vmware.com/sonobuoy/sonobuoy:v0.56.3"
  Warning  Failed     3s (x3 over 43s)   kubelet            Failed to pull image "projects.registry.vmware.com/sonobuoy/sonobuoy:v0.56.3": rpc error: code = NotFound desc = failed to pull and unpack image "projects.registry.vmware.com/sonobuoy/sonobuoy:v0.56.3": failed to resolve reference "projects.registry.vmware.com/sonobuoy/sonobuoy:v0.56.3": projects.registry.vmware.com/sonobuoy/sonobuoy:v0.56.3: not found
  Warning  Failed     3s (x3 over 43s)   kubelet            Error: ErrImagePull
```
I was able to successfully run it though by not specifying an image for sonobuoy in the line
`  ./sonobuoy run --kube-conformance-image=${SONOBUOY_CONFORMANCE_IMAGE} --mode=${SONOBUOY_MODE} --skip-preflight --plugin e2e --e2e-parallel ${SONOBUOY_PARALLEL} --wait 2>&1
` as it pulls from docker sonobuoy/sonobuoy by default.

**Comment by sombrafam** [comment]
Hi Adnan, thanks for taking the time to report this. I was able to reproduce this problem in my env. but hit on something else: "You have reached your pull rate limit", so, we need to discuss a way to have our own docker registry.
